class SavingsGoal {
  final int? id; // Primary key can be nullable since it's generated by SQLite
  final String name;
  final int targetAmount;
  final int savedAmount;

  SavingsGoal({
    this.id,
    required this.name,
    required this.targetAmount,
    required this.savedAmount,
  });

  // Convert a SavingsGoal into a Map. The keys must match the column names in SQLite.
  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'name': name,
      'targetAmount': targetAmount,
      'savedAmount': savedAmount,
    };
  }

  // Convert a Map into a SavingsGoal. This is used when fetching from the database.
  factory SavingsGoal.fromMap(Map<String, dynamic> map) {
    return SavingsGoal(
      id: map['id'],
      name: map['name'],
      targetAmount: map['targetAmount'],
      savedAmount: map['savedAmount'],
    );
  }
  double get progress {
    if (targetAmount <= 0) return 0.0; // Prevent division by zero
    return savedAmount / targetAmount;
  }
}



















/*class SavingsGoal {
  String name;
  int targetAmount;
  int savedAmount;

  SavingsGoal(
      {required this.name,
      required this.targetAmount,
      required this.savedAmount});

  double get progress {
    if (targetAmount <= 0) return 0.0; // Prevent division by zero
    return savedAmount / targetAmount;
  }
}
*/